### ISSUE TITLE
I/O voltage?

### ISSUE THREAD

**Issue by ErikAndren** [conorpp/efm8-arduino-programmer#4]
The AT mega is 5v and the EFM8bb1 is 3.3v? Do you need a level shifter in order to protect the efm8bb1?

**Comment by ErikAndren** [comment]
I successfully flashed it but used a level shifter inbetween. I still don't know if this is necessary or not.

**Comment by ciotlosm** [comment]
You need to have 3.3v You can use different power source as well to achieve this.
