### ISSUE TITLE
Can't flash anymore, I get 0x43

### ISSUE THREAD

**Issue by ciotlosm** [conorpp/efm8-arduino-programmer#5]
I tried to flash the device with a new Arduino, and I might have gotten the cables reversed (CD2D and C2CK). 

I get new:
```
Once
 * Running on http://127.0.0.1:4040/ (Press CTRL+C to quit)
Connected
x: 0x81
PI initiated
Device erased
0x0 0x0 020EF7ED24F8FEEFD39E4015ED2408FDE433FCC3EF9DEC6480F874809850028001C322020E678E438F448C458D46AB07AA06E4F9F87FE87E03FD1214039000C3E545F0A3E546F09000C1E543F0A3E544F043910422E59120E2FB2202100EE53675F00DA422F583E493FC740193FD22E4F5A92202120CD2011214A8C290C296D280E4FBFD7F101216321205CF74A4F0D2AFE4F52FF530D2960530E5307002052FB410F3E52FB427EEC2963001091213748E328F338006753201753300E5337004E532640170409000C6E07007F52FF5300202840530E5307002052FD39410E52F94274002D296D3E5309430E52F947550
x: 0x43
x: 0x43
x: 0x43
```

with the 0x43 going on forever

Based on the exception if I update the software to show it, I see:

```
Connected
x: 0x81
PI initiated
Device erased
0x0 0x0 020EF7ED24F8FEEFD39E4015ED2408FDE433FCC3EF9DEC6480F874809850028001C322020E678E438F448C458D46AB07AA06E4F9F87FE87E03FD1214039000C3E545F0A3E546F09000C1E543F0A3E544F043910422E59120E2FB2202100EE53675F00DA422F583E493FC740193FD22E4F5A92202120CD2011214A8C290C296D280E4FBFD7F101216321205CF74A4F0D2AFE4F52FF530D2960530E5307002052FB410F3E52FB427EEC2963001091213748E328F338006753201753300E5337004E532640170409000C6E07007F52FF5300202840530E5307002052FD39410E52F94274002D296D3E5309430E52F947550
Exception in prog: unpack requires a string argument of length 1
attempts: 1
Exception in conf: unpack requires a string argument of length 1
Exception in conf: unpack requires a string argument of length 1
Exception in conf: unpack requires a string argument of length 1
Exception in conf: unpack requires a string argument of length 1
x: 0x43
Exception in conf: 
x: 0x43
Exception in conf: 
x: 0x43
Exception in conf: 
x: 0x43
Exception in conf: 
```

I assume I get some sort of CRC error or something. Based on the error I assume the error is at line:
```
ret = struct.unpack('B', self.ser.read(1))[0]
```

**Comment by conorpp** [comment]
Did you try switching c2ck and c2d since you're not sure?

**Comment by ciotlosm** [comment]
Yes. Switching them doesn’t even get PI initiated. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by conorpp** [comment]
```
Exception in conf: unpack requires a string argument of length 1
```
What is happening is that `self.ser.read(1)` times out and returns an empty string.

`x: 0x43` is the return code from the arduino.  It looks like [it is a CRC error](https://github.com/conorpp/efm8-arduino-programmer/blob/master/prog/prog.ino#L326).

The CRC is calculated on Arduino after receiving a flash block from PC.  It doesn't write to the flash after it sees the CRC failed.  You could insert prints on the arduino to see what is wrong with the data.  You could also try reducing the baud rate.

https://github.com/conorpp/efm8-arduino-programmer/blob/master/prog/prog.ino#L247
https://github.com/conorpp/efm8-arduino-programmer/blob/master/prog_server.py#L13

**Comment by ciotlosm** [comment]
I will add some prints. The firmware is correct as I'm using https://github.com/Portisch/RF-Bridge-EFM8BB1/blob/master/Keil%208051%20v9.53%20-%20Release/RF_Bridge.hex which the guys are using successfully for tests. I previously was able to flash it, but now it's not working anymore. 

I will try the baud rate change and come back with details. Thanks for the help.

**Comment by ciotlosm** [comment]
@conorpp you're a genious. The serial speed was causing problems. I guess this is because the Arduino Uno I was using had a different serial converter (cheaper version) that probably didn't handle so well the speed set initially. 

I used 57600 and it worked like a charm.

**Comment by conorpp** [comment]
Glad it worked!
